### ISSUE TITLE
列表内容获取异常

### ISSUE THREAD

**Issue by karanotsingyu** [gxr404/BilibiliVideoDownloadFork#10]
继玄学的下载出错之后，列表获取也开始玄学了起来

比如这个列表 https://space.bilibili.com/27534330/channel/seriesdetail?sid=1244138 点播放全部 https://www.bilibili.com/list/27534330 

粘贴到下载器里获取到的内容不是这个清单，而是隔壁清单，人傻了

<img width="912" alt="Screenshot 2024-10-21 at 15 06 51" src="https://github.com/user-attachments/assets/76c1e80b-f9b0-47ea-92bc-cf7fee1d0924">

重复添加还是这样

**Comment by karanotsingyu** [comment]
这个突然又正常了，玄学

**Comment by karanotsingyu** [comment]
不过还是转圈圈或者加进下载列表后失败

**Comment by gxr404** [comment]
1.  两个链接一样 读取到列表也就不一样
```txt
https://www.bilibili.com/list/27534330?sid=1244138&spm_id_from=333.999.0.0&desc=1&oid=907869614&bvid=BV1aM4y1R77W

https://www.bilibili.com/list/27534330
```
复制第二个链接到浏览器 会重定向到 `https://www.bilibili.com/list/27534330?oid=113322494004907&bvid=BV1NvyPYrErG`
这个链接读取到的列表就是500多个视频

2. 转圈圈的问题 查了下大概是b站风控了读取链接时变成验证码的页面

<img width="1443" alt="SCR-20241021-nubh" src="https://github.com/user-attachments/assets/13c7fcba-a465-4da7-b0b8-81fb26a5509f">

风控的问题 尝试修复了下 可以试试 [v17](https://github.com/gxr404/BilibiliVideoDownloadFork/releases/tag/v0.0.17) 我这边试是没出现一直转圈圈的情况
