### ISSUE TITLE
无法批量视频下载

### ISSUE THREAD

**Issue by stonechougood** [gxr404/BilibiliVideoDownloadFork#13]
比如：https://www.bilibili.com/list/354757414?sid=1688918&desc=1&oid=795002468&bvid=BV1jC4y147BV

**Comment by gxr404** [comment]
什么表现呢 报什么错吗  我这边试表现正常
<img width="809" alt="SCR-20241209-guza" src="https://github.com/user-attachments/assets/7e1c5043-ed99-4c19-b8c0-0397dfd9ac8f">

**Comment by stonechougood** [comment]
> > 比如：[bilibili.com/list/354757414?sid=1688918&desc=1&oid=795002468&bvid=BV1jC4y147BV](https://www.bilibili.com/list/354757414?sid=1688918&desc=1&oid=795002468&bvid=BV1jC4y147BV)
> 
> 或者是否是关闭了 ”下载 ”下载到单独文件夹“的到单独文件夹“的选项，如果是 以于[v0.0.19](https://github.com/gxr404/BilibiliVideoDownloadFork/releases/tag/v0.0.19)修复
是的，我关闭了 
![QQ20241209-174908](https://github.com/user-attachments/assets/d40b6353-00bd-496b-a584-511892d31154)
下载到单独文件夹“

**Comment by stonechougood** [comment]
确实v0.0.19已修复，感谢
