### ISSUE TITLE
为什么我会下载失败

### ISSUE THREAD

**Issue by ebisuxx** [gxr404/BilibiliVideoDownloadFork#2]
每次在下载完音频阶段后，就会直接跳下载失败

电脑是20款intel的，系统为OS X 14.0(23A344)，软件版本为最新

视频如下
https://github.com/user-attachments/assets/8c1b05ac-9ac7-436f-82e6-9b6413b93f52

**Comment by gxr404** [comment]
> 每次在下载完音频阶段后，就会直接跳下载失败
> 
> 电脑是20款intel的，系统为OS X 14.0(23A344)，软件版本为最新
> 
> 视频如下 [user-attachments/assets/8c1b05ac-9ac7-436f-82e6-9b6413b93f52](https://github.com/user-attachments/assets/8c1b05ac-9ac7-436f-82e6-9b6413b93f52)

方便提供一下 失败的b站视频链接吗 我这边找到视频下载是正常的

 
<img width="797" alt="SCR-20240727-lrlv" src="https://github.com/user-attachments/assets/1dcedcf5-b928-4b89-82c1-0b110b28cab1">


还有最好先将之前失败的全都删除调后再试试 怕缓存影响的

**Comment by ebisuxx** [comment]
地址：https://www.bilibili.com/video/BV15v4y1v7Kz
刚刚试了下，还是下载失败了。看样子是合成失败

**Comment by gxr404** [comment]
> 地址：[bilibili.com/video/BV15v4y1v7Kz](https://www.bilibili.com/video/BV15v4y1v7Kz) 刚刚试了下，还是下载失败了。看样子是合成失败

是同个视频 我这边是正常的，
发下 `~/Library/Logs/bilibilivideodownloadFork/main.log`日志文件里面的内容吧

**Comment by ebisuxx** [comment]
[main.log](https://github.com/user-attachments/files/16400226/main.log)
如上，spawn Unknown system error -86

**Comment by gxr404** [comment]
> [main.log](https://github.com/user-attachments/files/16400226/main.log) 如上，spawn Unknown system error -86

查了下这个错误，试下在终端执行下 `softwareupdate --install-rosetta`
显示`Type A and press return to agree:` 然后输入 `A`

**Comment by ebisuxx** [comment]
我是intel mac，rosetta 2只能在mac with Apple silicon 上安装

**Comment by ebisuxx** [comment]
查了一圈，都是mac with Apple silicon才会出现这个问题

**Comment by ebisuxx** [comment]
破防了，想换电脑了

**Comment by gxr404** [comment]
你安装的是[bilibilivideodownloadFork-0.0.6.dmg](https://github.com/gxr404/BilibiliVideoDownloadFork/releases/download/v0.0.6/bilibilivideodownloadFork-0.0.6.dmg) 还是 [bilibilivideodownloadFork-0.0.6-arm64.dmg](https://github.com/gxr404/BilibiliVideoDownloadFork/releases/download/v0.0.6/bilibilivideodownloadFork-0.0.6-arm64.dmg)呢

**Comment by gxr404** [comment]
> 查了一圈，都是mac with Apple silicon才会出现这个问题

我查了也是😂

**Comment by ebisuxx** [comment]
> 你安装的是[bilibilivideodownloadFork-0.0.6.dmg](https://github.com/gxr404/BilibiliVideoDownloadFork/releases/download/v0.0.6/bilibilivideodownloadFork-0.0.6.dmg) 还是 [bilibilivideodownloadFork-0.0.6-arm64.dmg](https://github.com/gxr404/BilibiliVideoDownloadFork/releases/download/v0.0.6/bilibilivideodownloadFork-0.0.6-arm64.dmg)呢
前者，arm版我打不开

**Comment by ebisuxx** [comment]
> 你安装的是[bilibilivideodownloadFork-0.0.6.dmg](https://github.com/gxr404/BilibiliVideoDownloadFork/releases/download/v0.0.6/bilibilivideodownloadFork-0.0.6.dmg) 还是 [bilibilivideodownloadFork-0.0.6-arm64.dmg](https://github.com/gxr404/BilibiliVideoDownloadFork/releases/download/v0.0.6/bilibilivideodownloadFork-0.0.6-arm64.dmg)呢

前者，arm版我打不开

**Comment by gxr404** [comment]
> > 你安装的是[bilibilivideodownloadFork-0.0.6.dmg](https://github.com/gxr404/BilibiliVideoDownloadFork/releases/download/v0.0.6/bilibilivideodownloadFork-0.0.6.dmg) 还是 [bilibilivideodownloadFork-0.0.6-arm64.dmg](https://github.com/gxr404/BilibiliVideoDownloadFork/releases/download/v0.0.6/bilibilivideodownloadFork-0.0.6-arm64.dmg)呢
> 
> 前者，arm版我打不开

已修复，更新到 v0.0.7

**Comment by ebisuxx** [comment]
刚刚试了下，视频成功下载并合成。非常感谢你
