### ISSUE TITLE
会员视频无法下载

### ISSUE THREAD

**Issue by youzhui** [gxr404/BilibiliVideoDownloadFork#5]
https://www.bilibili.com/bangumi/play/ep835859?spm_id_from=333.999.0.0

例如上面的，显示解析错误

**Comment by gxr404** [comment]
登录的账号是 会员账号吗 😂
我不是会员账号没试过下载会员视频

**Comment by youzhui** [comment]
肯定是大会员账号，不只是会员视频，就像是这种普通视频，只要地址是这种格式，就解析错误。

https://www.bilibili.com/bangumi/play/ep835674?spm_id_from=333.999.0.0&from_spmid=666.25.episode.0

**Comment by gxr404** [comment]
非会员的这种格式已于`v0.0.9`修复, 会员的视频 我这边就无法测了有空的话麻烦帮忙测下😂

**Comment by youzhui** [comment]
会员视频解析错误：Error: TypeError: Cannot read properties of undefined (reading 'duration')

**Comment by gxr404** [comment]
> 肯定是大会员账号，不只是会员视频，就像是这种普通视频，只要地址是这种格式，就解析错误。
> 
> [bilibili.com/bangumi/play/ep835674?spm_id_from=333.999.0.0&from_spmid=666.25.episode.0](https://www.bilibili.com/bangumi/play/ep835674?spm_id_from=333.999.0.0&from_spmid=666.25.episode.0)

如果用非会员的连接弹窗后 点会员的那一集下载呢 会报错吗

**Comment by youzhui** [comment]
> > 肯定是大会员账号，不仅仅是会员视频，就像是这种普通视频，只要地址是这种格式，就解析错误。
> > [bilibili.com/bangumi/play/ep835674?spm_id_from=333.999.0.0&from_spmid=666.25.episode.0](https://www.bilibili.com/bangumi/play/ep835674?spm_id_from=333.999.0.0&from_spmid=666.25.episode.0)
> 
> 如果用非会员的连接弹窗后点会员的那一套下载呢会报错吗

会卡死

**Comment by gxr404** [comment]
试下用这个版本 看看 https://github.com/gxr404/BilibiliVideoDownloadFork/releases/tag/v0.0.10

我这边借了个号 试了下 没啥问题

**Comment by youzhui** [comment]
> 试下用这个版本看看https://github.com/gxr404/BilibiliVideoDownloadFork/releases/tag/v0.0.10
> 
> 我借了个号试了下没啥问题

是可以下载了，但是地址不对，显示的多P视频就不是视频本身

https://www.bilibili.com/bangumi/play/ep835914?spm_id_from=333.999.0.0

**Comment by gxr404** [comment]
没懂啥意思 该会员视频链接 是个合集 含其他多p视频 所以填入 [会员视频](https://www.bilibili.com/bangumi/play/ep835859?spm_id_from=333.999.0.0)和 [非会员视频](https://www.bilibili.com/bangumi/play/ep835674?spm_id_from=333.999.0.0&from_spmid=666.25.episode.0) 都会弹窗，如果只需下其中某一集 弹窗里选择即可

**Comment by youzhui** [comment]
> 没懂啥意思会员视频链接是个合集含其他多p视频所以填入[会员视频的](https://www.bilibili.com/bangumi/play/ep835859?spm_id_from=333.999.0.0)和[非会员视频](https://www.bilibili.com/bangumi/play/ep835674?spm_id_from=333.999.0.0&from_spmid=666.25.episode.0)都会弹窗，如果只需下其中一个集弹窗里选择即可

需要的视频就不在多p列表，你打开看一下，要下载是右侧列表里的，而不是上面的正片

**Comment by gxr404** [comment]
![SCR-20240919-rgsc](https://github.com/user-attachments/assets/7d715d83-9ace-47e0-8fa0-dc9c7247fee2)
你是指 要下载的 红框内的 而不是 蓝框内的？
这个有点特殊😂

**Comment by youzhui** [comment]
> ![SCR-20240919-rgsc](https://private-user-images.githubusercontent.com/17134256/368976220-7d715d83-9ace-47e0-8fa0-dc9c7247fee2.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NDcwOTMsIm5iZiI6MTcyNjc0Njc5MywicGF0aCI6Ii8xNzEzNDI1Ni8zNjg5NzYyMjAtN2Q3MTVkODMtOWFjZS00N2UwLThmYTAtZGM5YzcyNDdmZWUyLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQxMTUzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMjFmODc0MjVlYzY1NTkxNDMzOGNkZmY0YTA1YzU5ZWU0ZmVmZjhjODA3NDRiOGZhYzA0MTllNDE4MzhkYjFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Lkmy4KWb6HDPqol3veOcX9GW68O8Wj40SDsu3Z_li00) 你是指要下载的红框内的而不是蓝框内的？ 这个有点特殊😂

对，应该是B站隐藏了下方视频的真实地址，上面总挂着3个正片

**Comment by youzhui** [comment]
可以下载了，但是还有一点小瑕疵，
https://www.bilibili.com/bangumi/play/ep835859?spm_id_from=333.999.0.0
 这个视频有4K版本，但是上面的可选分辨率最高只有1080P高码率

**Comment by gxr404** [comment]
大概看了下 
如果使用 [仅支持1080P高码率的视频链接](https://www.bilibili.com/bangumi/play/ep835845?spm_id_from=333.999.0.0&from_spmid=666.25.episode.0)  打开弹窗 选项只有1080P高码率

如果使用 [支持4k的视频链接](https://www.bilibili.com/bangumi/play/ep835859?spm_id_from=333.999.0.0) 打开弹窗 就有 选项4k

**Comment by youzhui** [comment]
OK，完美解决，感谢大神！

**Comment by gxr404** [comment]
如果选择4k下载 视频仅支持1080高码率 则 会自动降级到1080高码率(降级功能一直都有)， 
只是现在v0.0.11版本显示有问题 没显示视频真实的分辨率，
在v0.0.12修复了
