### ISSUE TITLE
文件下载命名优化请求喵( • ̀ω•́ )✧

### ISSUE THREAD

**Issue by karanotsingyu** [gxr404/BilibiliVideoDownloadFork#8]
希望能改成 UP昵称-视频标题-视频ID喵，这样更方便批量管理文件喵 

以及list的批量下载能选择保留或移除掉文件名开头的“[P1]”这样的序号喵，毕竟多数时候合集内容不是连续的喵，而连续内容up主一般会自行命名好的喵

谢谢喵 ฅ/ᐠ˶> ﻌ<˶ᐟ\ฅ

**Comment by karanotsingyu** [comment]
靠 网卡了一下以为没提交 刷新页面就已经以鬼畜的形式提交了

**Comment by karanotsingyu** [comment]
顺便想请教一下一下这个工具是如何转m4s格式的

我用Bilibili客户端（今天才发现有Mac的了）下载缓存，找到了m4s文件，然后试着用ffmpeg来合并m4s为mp4失败了，删掉各种教程提到的开头的0也失败

**Comment by gxr404** [comment]
> 希望能改成 UP昵称-视频标题-视频ID喵，这样更方便批量管理文件喵
> 
> 以及list的批量下载能选择保留或移除掉文件名开头的“[P1]”这样的序号喵，毕竟多数时候合集内容不是连续的喵，而连续内容up主一般会自行命名好的喵
> 
> 谢谢喵 ฅ/ᐠ˶> ﻌ<˶ᐟ\ฅ

[v17](https://github.com/gxr404/BilibiliVideoDownloadFork/releases/tag/v0.0.17)文件名已调整可以试试

**Comment by gxr404** [comment]
> 顺便想请教一下一下这个工具是如何转m4s格式的
> 
> 我用Bilibili客户端（今天才发现有Mac的了）下载缓存，找到了m4s文件，然后试着用ffmpeg来合并m4s为mp4失败了，删掉各种教程提到的开头的0也失败

查了下大概脚本命令是:

```bash
ffmpeg -i video.m4s -i audio.m4s -y -acodec copy -vcodec copy result.mp4
```
可以参考下

**Comment by karanotsingyu** [comment]
> > 希望能改成 UP昵称-视频标题-视频ID喵，这样更方便批量管理文件喵
> > 以及list的批量下载能选择保留或移除掉文件名开头的“[P1]”这样的序号喵，毕竟多数时候合集内容不是连续的喵，而连续内容up主一般会自行命名好的喵
> > 谢谢喵 ฅ/ᐠ˶> ﻌ<˶ᐟ\ฅ
> 
> [v17](https://github.com/gxr404/BilibiliVideoDownloadFork/releases/tag/v0.0.17)文件名已调整可以试试

赞！
